#!/usr/bin/env python3
"""Flatten the mtop package into one runnable file.

The curl one-liner is a real part of this project's value: `mtop` is a thing
you drop onto a box you SSHed into, not a thing you pip-install there. The
package is split into submodules, so the release artifact is generated
instead of hand-maintained.

Submodules are embedded as source strings and exec'd into real module
objects registered in sys.modules under their package names, rather than
concatenated. Concatenation would let same-named helpers (`_read`,
`IS_LINUX`, ...) clobber each other depending on file order — a bug that
only shows up at runtime, on someone else's machine.

Submodules may import each other with relative imports (`from .util import
run_cmd`): a synthetic `mtop` package is registered first and every module
runs with `__package__ = "mtop"`, so the import system finds the already
loaded siblings in sys.modules. Modules are embedded in dependency order
(depth-first over their relative imports), which also rejects cycles.

Usage: python tools/bundle.py [-o dist/mtop.py]
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG = ROOT / "src" / "mtop"

# `from .gpu import (A, B,\n  C)` / `from .gpu import A` / `from . import a, b`
IMPORT_RE = re.compile(
    r"^from \.(?P<mod>\w*) import (?:\((?P<multi>[^)]*)\)|(?P<single>[^\n(]+))$",
    re.MULTILINE,
)

LOADER = '''
# ── bundled submodules (generated by tools/bundle.py — do not edit) ──────────
import sys as _sys
import types as _types

_pkg = _types.ModuleType("mtop")
_pkg.__path__ = []                      # marks it as a package for relative imports
_pkg.__file__ = "<bundled:mtop>"
_sys.modules["mtop"] = _pkg


def _bundle_load(name: str, source: str):
    mod = _types.ModuleType(name)
    mod.__file__ = "<bundled:%s>" % name
    mod.__package__ = "mtop"
    exec(compile(source, "mtop/%s.py" % name.rsplit(".", 1)[-1], "exec"),
         mod.__dict__)
    _sys.modules[name] = mod
    setattr(_pkg, name.rsplit(".", 1)[-1], mod)
    return mod

'''


# Any relative import, including ones inside functions (cli imports ui lazily
# so the headless modes never load curses) — those must be embedded too.
DEP_RE = re.compile(
    r"^[ \t]*from \.(?P<mod>\w*) import (?:\((?P<multi>[^)]*)\)|(?P<single>[^\n(]+))$",
    re.MULTILINE,
)


def deps_of(src: str) -> list[str]:
    """Sibling modules a source imports relatively, in first-seen order."""
    out: list[str] = []
    for m in DEP_RE.finditer(src):
        mod = m.group("mod")
        if mod == "":                                   # from . import a, b
            names = (m.group("multi") or m.group("single")).split(",")
            for n in names:
                n = n.strip().split(" as ")[0].strip()
                if n and n not in out:
                    out.append(n)
        elif mod not in out:
            out.append(mod)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--output", default=str(ROOT / "dist" / "mtop.py"))
    args = ap.parse_args()

    main_src = (PKG / "__init__.py").read_text()
    sources: dict[str, str] = {}
    order: list[str] = []
    visiting: list[str] = []

    def load(mod: str) -> None:
        if mod in order:
            return
        if mod in visiting:
            raise SystemExit(f"import cycle: {' -> '.join(visiting + [mod])}")
        path = PKG / f"{mod}.py"
        if not path.exists():
            raise SystemExit(f"src/mtop/{mod}.py not found (imported relatively)")
        src = path.read_text()
        if "'''" in src:
            raise SystemExit(
                f"src/mtop/{mod}.py contains ''' — the bundler embeds "
                "sources as r'''...''' literals. Use \"\"\" instead.")
        visiting.append(mod)
        for dep in deps_of(src):
            load(dep)
        visiting.pop()
        sources[mod] = src
        order.append(mod)

    for dep in deps_of(main_src):
        load(dep)

    embeds = [f"_mod_{m} = _bundle_load('mtop.{m}', r'''\n{sources[m]}\n''')" for m in order]

    bindings: list[str] = []

    def replace(match: re.Match) -> str:
        mod = match.group("mod")
        names = [n.strip() for n in
                 (match.group("multi") or match.group("single")).split(",") if n.strip()]
        for n in names:
            if " as " in n:
                orig, alias = (x.strip() for x in n.split(" as "))
            else:
                orig = alias = n
            if mod == "":
                bindings.append(f"{alias} = _mod_{orig}")
            else:
                bindings.append(f"{alias} = _mod_{mod}.{orig}")
        return f"# (bundled) {match.group(0).splitlines()[0]}"

    main_src = IMPORT_RE.sub(replace, main_src)
    if not embeds:
        print("warning: no relative imports found — nothing to bundle", file=sys.stderr)

    block = LOADER + "\n".join(embeds) + "\n\n" + "\n".join(bindings) + "\n"

    # Insert after the module docstring so `head -20 mtop.py` still explains
    # what the file is.
    marker = '"""\n'
    idx = main_src.index(marker, main_src.index(marker) + len(marker)) + len(marker)
    out_src = main_src[:idx] + block + main_src[idx:]
    # The bundled file is a script, not the package: make `main()` reachable.
    out_src += "\n\nif __name__ == \"__main__\":\n    main()\n"

    out = pathlib.Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(out_src)
    out.chmod(0o755)
    compile(out_src, str(out), "exec")  # fail loudly here, not on the user's box
    print(f"wrote {out} ({len(out_src.splitlines())} lines, "
          f"{len(order)} embedded module(s): {', '.join(order)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
