#!/usr/bin/env python3
"""Flatten the mtop package into one runnable file.

The curl one-liner is a real part of this project's value: `mtop` is a thing
you drop onto a box you SSHed into, not a thing you pip-install there. The
0.4.0 split into submodules would have broken it, so the release artifact is
generated instead of hand-maintained.

Submodules are embedded as source strings and exec'd into real module objects
registered in sys.modules, rather than concatenated. Concatenation would let
same-named helpers (`_read`, `IS_LINUX`, ...) clobber each other depending on
file order — a bug that only shows up at runtime, on someone else's machine.

Usage: python tools/bundle.py [-o dist/mtop.py]
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG = ROOT / "src" / "mtop"

# `from .gpu import (A, B,\n  C)` — single or parenthesized multi-line.
IMPORT_RE = re.compile(
    r"^from \.(?P<mod>\w+) import (?:\((?P<multi>[^)]*)\)|(?P<single>[^\n(]+))$",
    re.MULTILINE,
)

LOADER = '''
# ── bundled submodules (generated by tools/bundle.py — do not edit) ──────────
import sys as _sys
import types as _types


def _bundle_load(name: str, source: str):
    mod = _types.ModuleType(name)
    mod.__file__ = "<bundled:%s>" % name
    exec(compile(source, "mtop/%s.py" % name.rsplit(".", 1)[-1], "exec"),
         mod.__dict__)
    _sys.modules[name] = mod
    return mod

'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--output", default=str(ROOT / "dist" / "mtop.py"))
    args = ap.parse_args()

    main_src = (PKG / "__init__.py").read_text()

    embeds: list[str] = []
    bindings: list[str] = []
    seen: set[str] = set()

    def replace(match: re.Match) -> str:
        mod = match.group("mod")
        names = [n.strip() for n in
                 (match.group("multi") or match.group("single")).split(",")
                 if n.strip()]
        if mod not in seen:
            seen.add(mod)
            src = (PKG / f"{mod}.py").read_text()
            if "'''" in src:
                raise SystemExit(
                    f"src/mtop/{mod}.py contains ''' — the bundler embeds "
                    "sources as r'''...''' literals. Use \"\"\" instead.")
            embeds.append(f"_mod_{mod} = _bundle_load('mtop.{mod}', r'''\n{src}\n''')")
        for n in names:
            if " as " in n:
                orig, alias = (x.strip() for x in n.split(" as "))
                bindings.append(f"{alias} = _mod_{mod}.{orig}")
            else:
                bindings.append(f"{n} = _mod_{mod}.{n}")
        return f"# (bundled) from .{mod} import {', '.join(names)}"

    main_src = IMPORT_RE.sub(replace, main_src)

    if not embeds:
        print("warning: no relative imports found — nothing to bundle",
              file=sys.stderr)

    block = LOADER + "\n".join(embeds) + "\n\n" + "\n".join(bindings) + "\n"

    # Insert after the module docstring so `head -20 mtop.py` still explains
    # what the file is.
    marker = '"""\n'
    idx = main_src.index(marker, main_src.index(marker) + len(marker)) + len(marker)
    out_src = main_src[:idx] + block + main_src[idx:]

    out = pathlib.Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(out_src)
    out.chmod(0o755)
    compile(out_src, str(out), "exec")  # fail loudly here, not on the user's box
    print(f"wrote {out} ({len(out_src.splitlines())} lines, "
          f"{len(seen)} embedded module(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
